arch:
  - s390x
services:
  - docker
before_script:
  - docker build -t aosadchyy/uperf:manifest-s390x --build-arg ARCH=s390x/ .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin docker.io
script:
  - docker push aosadchyy/uperf:manifest-s390x
after_script:
  - docker images