apiVersion: v1
kind: Service
metadata:
  name: uperf-server
spec:
  ports:
    - port: 20000
      protocol: TCP
      name: tcp-uperf
    - port: 20001
      protocol: UDP
      name: udp-uperf
  selector:
    app: uperf-server